ln -s amiga_wb1_normal arrow
ln -s amiga_wb1_diagonal1 bd_double_arrow
ln -s amiga_wb1_normal bottom_left_corner
ln -s amiga_wb1_normal bottom_right_corner
ln -s amiga_wb1_normal bottom_side
ln -s amiga_wb1_normal bottom_tee
ln -s amiga_wb1_unavailable circle
ln -s amiga_wb1_normal color-picker
ln -s amiga_wb1_normal copy
ln -s amiga_wb1_normal cross
ln -s amiga_wb1_unavailable crossed_circle
ln -s amiga_wb1_precision crosshair
ln -s amiga_wb1_normal cross_reverse
ln -s amiga_wb1_precision diamond_cross
ln -s amiga_wb1_normal dnd-ask
ln -s amiga_wb1_normal dnd-copy
ln -s amiga_wb1_normal dnd-link
ln -s amiga_wb1_normal dnd-move
ln -s amiga_wb1_normal dnd-none
ln -s amiga_wb1_normal dotbox
ln -s amiga_wb1_normal dot_box_mask
ln -s amiga_wb1_vertical double_arrow
ln -s amiga_wb1_normal draft_large
ln -s amiga_wb1_normal draft_small
ln -s amiga_wb1_normal draped_box
ln -s amiga_wb1_diagonal2 fd_double_arrow
ln -s amiga_wb1_normal fleur
ln -s amiga_wb1_normal grabbing
ln -s amiga_wb1_link hand
ln -s amiga_wb1_link hand1
ln -s amiga_wb1_link hand2
ln -s amiga_wb1_horizontal h_double_arrow
ln -s amiga_wb1_help help
ln -s amiga_wb1_normal icon
ln -s amiga_wb1_normal left_ptr
ln -s amiga_wb1_help left_ptr_help
ln -s amiga_wb1_work left_ptr_watch
ln -s amiga_wb1_normal left_side
ln -s amiga_wb1_normal left_tee
ln -s amiga_wb1_normal link
ln -s amiga_wb1_normal ll_angle
ln -s amiga_wb1_normal lr_angle
ln -s amiga_wb1_normal move
ln -s amiga_wb1_normal pencil
ln -s amiga_wb1_normal pirate
ln -s amiga_wb1_normal plus
ln -s amiga_wb1_normal question_arrow
ln -s amiga_wb1_normal right_ptr
ln -s amiga_wb1_normal right_side
ln -s amiga_wb1_normal right_tee
ln -s amiga_wb1_normal sb_down_arrow
ln -s amiga_wb1_horizontal sb_h_double_arrow
ln -s amiga_wb1_normal sb_left_arrow
ln -s amiga_wb1_normal sb_right_arrow
ln -s amiga_wb1_normal sb_up_arrow
ln -s amiga_wb1_vertical sb_v_double_arrow
ln -s amiga_wb1_normal target
ln -s amiga_wb1_normal tcross
ln -s amiga_wb1_normal top_left_arrow
ln -s amiga_wb1_normal top_left_corner
ln -s amiga_wb1_normal top_right_corner
ln -s amiga_wb1_normal top_side
ln -s amiga_wb1_normal top_tee
ln -s amiga_wb1_normal ul_angle
ln -s amiga_wb1_normal ur_angle
ln -s amiga_wb1_vertical v_double_arrow
ln -s amiga_wb1_busy watch
ln -s amiga_wb1_normal X_cursor
ln -s amiga_wb1_normal xterm
